version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dj_commerce_api_uzzal
      POSTGRES_PASSWORD: dj_commerce_api_testpass123
      POSTGRES_DB: dj_commerce_api

  redis:
    image: "redis:6"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A core worker -l info -E
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A core beat -l info
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A core flower
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - celery
      - redis

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
